# Blob storage connections used for experiment datasets.
# Profiles allow switching between environments (dev, staging, prod, etc.).
#
# SECURITY WARNING: This file is now in .gitignore. Add your real credentials here.
# Use the template (blob_store.yaml.template) as a reference.
#
# NEVER commit real SAS tokens or credentials to git!

default:
  connection_name: "workspaceblobstore"
  azureml_datastore_uri: "azureml://subscriptions/b1a4da9f-5275-4cc8-85ec-b2fd2236538c/resourcegroups/AI_Sandpit/workspaces/cto_poc_sourcing1/datastores/workspaceblobstore/paths/UI/2025-08-21_191420_UTC/PCS100-22.08.25.csv"
  account_name: "elspethsyntheticdata"
  container_name: "elspethdatasource"
  blob_path: "SyntheticData.csv"
  # Add your SAS token here (this file is now in .gitignore):
  sas_token: "REPLACE_WITH_YOUR_SAS_TOKEN"
  # Or use DefaultAzureCredential by omitting sas_token entirely
