# Sample suite settings leveraging the mock LLM and local CSV datasource.

default:
  datasource:
    plugin: local_csv
    determinism_level: guaranteed
    options:
      retain_local: false
      path: config/sample_suite/data/sample_input.csv
      # Schema validation: Declare expected columns with types
      # This enables fail-fast validation at config-time instead of row 501
      schema:
        APPID: str
        title: str
        summary: str
        industry: str
  llm:
    plugin: mock
    determinism_level: high
    options:
      seed: 42
  sinks:
    - plugin: csv
      determinism_level: guaranteed
      options:
        path: outputs/sample_suite/latest_results.csv
  prompt_packs:
    sample:
      prompts:
        system: |
          You are an evaluation assistant that returns concise JSON feedback.
        user: |
          Evaluate application {{ APPID }} titled "{{ title }}".
          {% if industry %}Industry: {{ industry }}.{% endif %}
          Summary: {{ summary }}.
          Return JSON {"score": <0-1>, "comment": "<insight>"}.
      prompt_fields:
        - APPID
        - title
        - summary
        - industry
      prompt_defaults:
        industry: ""
      criteria:
        - name: analysis
          template: |
            Provide JSON {"score": <0-1>, "comment": "<analysis>"} assessing clarity of summary for {{ APPID }}.
        - name: prioritization
          template: |
            Estimate priority (0-1) for {{ APPID }} considering industry "{{ industry|default('general', boolean=true) }}".
      row_plugins:
        - name: score_extractor
          determinism_level: guaranteed
          options:
            key: score
            parse_json_content: true
            allow_missing: false
            threshold_mode: gte
            flag_field: score_flags
            threshold: 0.7
      aggregator_plugins:
        - name: score_stats
          determinism_level: guaranteed
        - name: score_recommendation
          determinism_level: guaranteed
      baseline_plugins:
        - name: score_delta
          determinism_level: guaranteed
  prompt_pack: sample
  suite_defaults:
    prompt_pack: sample
    concurrency:
      enabled: true
      max_workers: 4
      backlog_threshold: 2
      utilization_pause: 0.9
