# Example: Azure Cognitive Search retrieval with request_timeout

retrieval:
  provider: azure_search
  endpoint: https://my-search.search.windows.net
  index: elspeth-experiments
  api_key_env: AZURE_SEARCH_KEY
  # New option: bound per-query latency (seconds). Alias: timeout
  request_timeout: 20
  vector_field: embedding
  namespace_field: namespace
  content_field: contents
  top_k: 3
  min_score: 0.4

