name: Auto-bump Semgrep Pin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

permissions:
  read-all: true

jobs:
  bump-semgrep-pin:
    name: Bump Semgrep Docker tag@digest
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.12'

      - id: bump
        name: Update Semgrep pin
        run: |
          python scripts/update_semgrep_pin.py

      - name: Select PR token
        run: |
          if [ -n "${{ secrets.PR_AUTOBUMP_TOKEN }}" ]; then
            echo "PR_TOKEN=${{ secrets.PR_AUTOBUMP_TOKEN }}" >> $GITHUB_ENV
          else
            echo "PR_TOKEN=${{ github.token }}" >> $GITHUB_ENV
          fi

      - name: Create pull request
        if: steps.bump.outputs.UPDATED == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ env.PR_TOKEN }}
          branch: chore/semgrep-pin
          title: 'CI: Bump Semgrep image to ${{ steps.bump.outputs.NEW_TAG }}'
          commit-message: 'CI: Bump Semgrep image to ${{ steps.bump.outputs.NEW_TAG }} @ ${{ steps.bump.outputs.NEW_DIGEST }}'
          add-paths: |
            .github/workflows/ci.yml
          body: |
            Bump the Semgrep CLI Docker image pin in `.github/workflows/ci.yml`.

            - Tag: `${{ steps.bump.outputs.NEW_TAG }}`
            - Digest: `${{ steps.bump.outputs.NEW_DIGEST }}`

            This keeps security scans on the latest Semgrep release with a pinned digest for supply-chain hardening.
          labels: |
            ci
            security
          sign-commits: true
          delete-branch: true
