name: Auto-bump Grype Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'

permissions:
  contents: write
  pull-requests: write
  workflows: write

jobs:
  bump-grype:
    name: Bump Anchore Grype version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.12'

      - id: bump
        name: Update Grype version in workflows
        run: |
          python scripts/update_grype_version.py

      - name: Select PR token
        run: |
          if [ -n "${{ secrets.PR_AUTOBUMP_TOKEN }}" ]; then
            echo "PR_TOKEN=${{ secrets.PR_AUTOBUMP_TOKEN }}" >> $GITHUB_ENV
          else
            echo "PR_TOKEN=${{ github.token }}" >> $GITHUB_ENV
          fi

      - name: Create pull request
        if: steps.bump.outputs.UPDATED == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ env.PR_TOKEN }}
          branch: chore/bump-grype
          title: 'CI: Bump Grype to ${{ steps.bump.outputs.NEW_VERSION }}'
          commit-message: 'CI: Bump Grype to ${{ steps.bump.outputs.NEW_VERSION }}'
          add-paths: |
            .github/workflows/ci.yml
            .github/workflows/publish.yml
          body: |
            Bump Anchore Grype version used by CI to `${{ steps.bump.outputs.NEW_VERSION }}`.

            This keeps vulnerability scanning up to date with the latest Grype release.
          labels: |
            ci
            security
            dependencies
          sign-commits: true
          delete-branch: true

