name: SonarQube Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  ci-core:
    name: CI Core (Lint, Types, Tests)
    uses: tachyon-beep/elspeth/.github/workflows/reusable-ci.yml@1aed7191970eb9d35716a282b8b08a091fc1a816
    with:
      python-version: '3.12'
    permissions:
      contents: read

  sonarqube:
    name: Run SonarQube Scan
    runs-on: ubuntu-latest
    needs: ci-core
    permissions:
      contents: read
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY || 'tachyon-beep_elspeth' }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION || 'tachyon-beep' }}
      SONAR_HOST_URL: https://sonarcloud.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # full history improves relevancy of Sonar analysis

      - name: Download coverage artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: coverage-xml
          path: .

      - name: SonarQube Scan
        if: env.SONAR_PROJECT_KEY != '' && env.SONAR_ORGANIZATION != ''
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
