name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Run SonarQube Scan
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY || 'tachyon-beep_elspeth' }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION || 'tachyon-beep' }}
      SONAR_HOST_URL: https://sonarcloud.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history improves relevancy of Sonar analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (locked)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools
          python -m piptools sync requirements-dev.lock
          python -m pip install -e . --no-deps

      - name: Run tests with coverage
        run: pytest --cov=elspeth --cov-report=term-missing --cov-report=xml:coverage.xml

      - name: SonarQube Scan
        if: env.SONAR_PROJECT_KEY != '' && env.SONAR_ORGANIZATION != ''
        # Pin to specific commit SHA for security (v6.1.0 - latest stable as of 2025-10)
        uses: SonarSource/sonarqube-scan-action@884b79409bbd464b2a59edc326a4b77dc56b2195
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
