name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Run SonarQube Scan
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      PIP_NO_CACHE_DIR: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY || 'tachyon-beep_elspeth' }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION || 'tachyon-beep' }}
      SONAR_HOST_URL: https://sonarcloud.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # full history improves relevancy of Sonar analysis

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            requirements-dev.lock

      - name: Install dependencies (locked)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools
          python -m piptools sync requirements-dev.lock
          python -m pip install -e . --no-deps

      - name: Run tests with coverage
        run: pytest --cov=elspeth --cov-report=term-missing --cov-report=xml:coverage.xml

      - name: SonarQube Scan
        if: env.SONAR_PROJECT_KEY != '' && env.SONAR_ORGANIZATION != ''
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
