name: Lint, Tests & Sample Suite

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  secrets-scan:
    name: Secret Scan (gitleaks)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: results.sarif

  lint-and-test:
    name: Lint, Tests, Supply-Chain Gates
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: secrets-scan
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (locked)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools
          python -m piptools sync requirements-dev.lock
          python -m pip install -e . --no-deps

      - name: Verify environment matches lockfile (dev)
        run: |
          python scripts/verify_locked_install.py -r requirements-dev.lock

      - name: Validate configuration templates (YAML syntax)
        run: |
          python scripts/validate_templates.py

      - name: Lint (ruff + mypy)
        run: python -m ruff check src tests && python -m mypy src

      - name: Security static analysis (bandit)
        run: |
          # Pin bandit to a specific version to avoid tool drift
          python -m pip install bandit==1.8.6
          # Fail build on HIGH severity and HIGH confidence findings
          bandit -q -r src --severity-level high --confidence-level high -f json -o bandit.json
      - name: Upload bandit report (JSON)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-json
          path: bandit.json

      - name: Install Semgrep (pinned)
        run: |
          # Pin semgrep to a specific version for deterministic results
          python -m pip install semgrep==1.92.0

      - name: Semgrep scan (CLI, curated)
        run: |
          # Curated, low-noise ruleset; block only ERROR-severity findings; disable metrics
          semgrep scan --config p/ci --severity ERROR --metrics=off --sarif -o semgrep.sarif
        continue-on-error: false

      - name: Upload semgrep report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif

      - name: Upload semgrep SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@42213152a85ae7569bdb6bec7bcd74cd691bfe41 # v3.30.9
        with:
          sarif_file: semgrep.sarif
          category: semgrep-oss

      - name: Unit tests with coverage
        run: python -m pytest -m "not slow" --maxfail=1 --disable-warnings --cov-fail-under=80 --cov-report=xml:coverage.xml

      - name: Enforce per-file coverage minimums
        run: |
          python scripts/check_coverage_thresholds.py \
            --file src/elspeth/cli.py:0.85 \
            --file src/elspeth/plugins/nodes/sinks/repository.py:0.85

      - name: Generate SBOM (requirements.lock)
        run: |
          python -m cyclonedx_py requirements requirements.lock --output-format JSON --output-file sbom.json --output-reproducible

      - name: Upload SBOM artefact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-json
          path: sbom.json

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Run pip-audit
        run: pip-audit -r requirements.lock --require-hashes --format json --output pip-audit.json

      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: pip-audit.json

  sample-suite:
    name: Sample Suite Smoke Test
    runs-on: ubuntu-latest
    needs: lint-and-test
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (locked)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools
          python -m piptools sync requirements-dev.lock
          python -m pip install -e . --no-deps

      - name: Run sample suite smoke test
        run: |
          python -m elspeth.cli \
            --settings config/sample_suite/settings.yaml \
            --suite-root config/sample_suite \
            --head 0 \
            --live-outputs

  container:
    name: Container Build, Test, and SBOMs
    runs-on: ubuntu-latest
    needs: lint-and-test
    timeout-minutes: 30
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Use pinned digest if provided
        id: pinfile
        run: |
          if [ -f .github/base-image.txt ]; then
            echo "Using pinned base image from .github/base-image.txt" && cat .github/base-image.txt
            echo "DOCKER_PYTHON_IMAGE=$(cat .github/base-image.txt)" >> $GITHUB_ENV
          fi

      - name: Resolve base image digest (linux/amd64)
        run: |
          if [ -z "${DOCKER_PYTHON_IMAGE}" ]; then
            docker pull --platform=linux/amd64 python:3.12.12-slim
            DIGEST=$(docker inspect --format='{{range .RepoDigests}}{{println .}}{{end}}' python:3.12.12-slim | grep '^python@sha256:' | head -n1 | cut -d'@' -f2)
            echo "DOCKER_PYTHON_IMAGE=python:3.12.12-slim@${DIGEST}" >> $GITHUB_ENV
          fi

      - name: Build dev/test image
        run: |
          docker build --build-arg PYTHON_IMAGE=$DOCKER_PYTHON_IMAGE --target dev -t elspeth:devtest .

      - name: Run tests in container
        run: |
          docker run --rm elspeth:devtest pytest -m "not slow" --maxfail=1 --disable-warnings --cov-fail-under=80

      - name: Build runtime image
        run: |
          docker build --build-arg PYTHON_IMAGE=$DOCKER_PYTHON_IMAGE --target runtime -t elspeth:runtime .

      - name: Generate runtime SBOM (app graph) inside container
        run: |
          docker run --rm \
            -v "$PWD/pyproject.toml:/tmp/pyproject.toml:ro" \
            elspeth:devtest sh -c '
              /opt/venv/bin/cyclonedx-py environment --pyproject /tmp/pyproject.toml --of JSON --output-reproducible -o /tmp/sbom-runtime.json && \
              cat /tmp/sbom-runtime.json' > sbom-runtime.json

      # Replace curl|sh installers with pinned GitHub Actions for Syft and Grype
      - name: Generate image SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@8d0a6505bf28ced3e85154d13dc6af83299e13f1 # v0.17.4
        with:
          image: elspeth:runtime
          format: cyclonedx-json
          output-file: sbom-image.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: container-sboms
          path: "sbom-runtime.json\nsbom-image.json"
      - name: Vulnerability scan (Grype) - block on HIGH
        id: grype
        uses: anchore/scan-action@4be3c24559b430723e51858969965e163b196957 # v3.3.5
        with:
          image: elspeth:runtime
          severity-cutoff: high
          fail-build: true
          output-format: sarif
          grype-version: v0.83.0
        env:
          GRYPE_DB_CACHE_DIR: ${{ runner.temp }}/grype-db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Grype SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@42213152a85ae7569bdb6bec7bcd74cd691bfe41 # v3.30.9
        with:
          sarif_file: ${{ steps.grype.outputs.sarif }}
          category: grype

      - name: Upload Grype SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-sarif
          path: ${{ steps.grype.outputs.sarif }}
