name: Performance Baselines (Isolated)

permissions: {}

on:
  workflow_dispatch:
  pull_request:

jobs:
  perf-tests:
    name: Run performance baseline tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Override CI env so tests are not skipped
    env:
      CI: "false"
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements-dev.lock

      - name: Install dependencies (locked)
        run: |
          python -m pip install -r requirements-dev.lock --require-hashes
          python -m pip install -e . --no-deps --no-index --no-build-isolation

      - name: Run performance tests only
        run: |
          python -m pytest -q tests/test_performance_baseline.py
