name: Build, Scan, Sign, and Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      COSIGN_OIDC_AUDIENCE: ${{ secrets.COSIGN_OIDC_AUDIENCE }}
      COSIGN_ID_TOKEN: ${{ secrets.COSIGN_ID_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Resolve base image digest (linux/amd64)
        run: |
          docker pull --platform=linux/amd64 python:3.12.12-slim
          DIGEST=$(docker inspect --format='{{range .RepoDigests}}{{println .}}{{end}}' python:3.12.12-slim | grep '^python@sha256:' | head -n1 | cut -d'@' -f2)
          echo "DOCKER_PYTHON_IMAGE=python:3.12.12-slim@${DIGEST}" >> $GITHUB_ENV

      - name: Build runtime image (version tag only)
        run: |
          VERSION=${GITHUB_REF_NAME}
          docker build --build-arg PYTHON_IMAGE=${{ env.DOCKER_PYTHON_IMAGE }} --target runtime -t ghcr.io/${{ github.repository }}:${VERSION} .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push runtime image (version tag only)
        run: |
          VERSION=${GITHUB_REF_NAME}
          docker push ghcr.io/${{ github.repository }}:${VERSION}

      - name: Install Syft and Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate image SBOM (CycloneDX JSON)
        run: |
          syft packages ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME} -o cyclonedx-json > sbom-image.json

      - name: Vulnerability scan (Grype) — block on HIGH
        run: |
          grype ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME} -o sarif --fail-on high > grype.sarif

      - name: Upload Grype SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype.sarif
          category: grype

      - name: Upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifacts
          path: |
            sbom-image.json
            grype.sarif

      - name: Install Cosign
        if: ${{ env.COSIGN_KEY != '' || (env.COSIGN_OIDC_AUDIENCE != '' && env.COSIGN_ID_TOKEN != '') }}
        uses: sigstore/cosign-installer@v3

      - name: Cosign keyless sign (optional)
        if: ${{ env.COSIGN_KEY == '' }}
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME} || true

      - name: Cosign key sign (optional)
        if: ${{ env.COSIGN_KEY != '' }}
        run: |
          echo "${{ env.COSIGN_KEY }}" > cosign.key
          export COSIGN_PASSWORD="${{ env.COSIGN_PASSWORD }}"
          cosign sign --key cosign.key ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME}
          rm -f cosign.key

      - name: Cosign attest SBOM (optional)
        if: ${{ env.COSIGN_KEY != '' }}
        run: |
          echo "${{ env.COSIGN_KEY }}" > cosign.key
          export COSIGN_PASSWORD="${{ env.COSIGN_PASSWORD }}"
          cosign attest --key cosign.key --predicate sbom-image.json --type cyclonedx ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME}
          rm -f cosign.key
