name: Build, Scan, Sign, and Publish

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write
      attestations: write
      id-token: write
    concurrency:
      group: publish-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      COSIGN_KMS_URI: ${{ secrets.COSIGN_KMS_URI }} # optional: e.g., awskms://..., gcpkms://..., azurekeyvault://...
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Read pinned base image digest
        run: |
          if [ ! -f .github/base-image.txt ]; then
            echo "Pinned base image not found. Please run the 'Repin Base Image Digest' workflow or add .github/base-image.txt." >&2
            exit 1
          fi
          echo "DOCKER_PYTHON_IMAGE=$(cat .github/base-image.txt)" >> $GITHUB_ENV

      - name: Build runtime image (version tag only)
        env:
          REPO: ${{ github.repository }}
        run: |
          VERSION=${GITHUB_REF_NAME}
          docker build --build-arg PYTHON_IMAGE=${{ env.DOCKER_PYTHON_IMAGE }} --target runtime -t ghcr.io/${REPO}:${VERSION} .

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push runtime image (version tag only)
        env:
          REPO: ${{ github.repository }}
        run: |
          VERSION=${GITHUB_REF_NAME}
          docker push ghcr.io/${REPO}:${VERSION}

      - name: Resolve pushed image digest
        id: image_digest
        env:
          REPO: ${{ github.repository }}
        run: |
          VERSION=${GITHUB_REF_NAME}
          REF=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${REPO}:${VERSION})
          DIGEST=${REF#*@}
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

      - name: Attest image provenance (SLSA)
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.image_digest.outputs.digest }}
          push-to-registry: true

      - name: Generate image SBOM (CycloneDX JSON)
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          format: cyclonedx-json
          output-file: sbom-image.json

      - name: Upload SBOM to GitHub Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
        with:
          tag_name: ${{ github.ref_name }}
          files: sbom-image.json
          fail_on_unmatched_files: true

      - name: "Vulnerability scan (Grype) — block on HIGH"
        id: grype
        uses: anchore/scan-action@568b89d27fc18c60e56937bff480c91c772cd993 # v7.1.0
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          severity-cutoff: high
          fail-build: true
          output-format: sarif
          grype-version: v0.101.1
        env:
          GRYPE_DB_CACHE_DIR: ${{ runner.temp }}/grype-db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Grype SARIF to code scanning
        if: always() && steps.grype.outputs.sarif != ''
        uses: github/codeql-action/upload-sarif@4e94bd11f71e507f7f87df81788dff88d1dacbfb # v4.31.0
        with:
          sarif_file: ${{ steps.grype.outputs.sarif }}
          category: grype

      - name: Upload publish artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: publish-artifacts
          path: |
            sbom-image.json
            ${{ steps.grype.outputs.sarif }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: "Sign image (required: prefer KMS/key if provided, else keyless OIDC)"
        env:
          COSIGN_EXPERIMENTAL: "1" # enable keyless OIDC flow
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          IMAGE="ghcr.io/${REPO}:${GITHUB_REF_NAME}"
          if [ -n "${COSIGN_KMS_URI:-}" ]; then
            echo "Signing with KMS: ${COSIGN_KMS_URI}"
            cosign sign --yes --key "${COSIGN_KMS_URI}" "${IMAGE}"
          elif [ -n "${COSIGN_KEY:-}" ]; then
            echo "Signing with provided key material"
            echo "${COSIGN_KEY}" > cosign.key
            export COSIGN_PASSWORD="${COSIGN_PASSWORD:-}"
            cosign sign --yes --key cosign.key "${IMAGE}"
            rm -f cosign.key
          else
            echo "Signing keylessly via GitHub OIDC"
            cosign sign --yes "${IMAGE}"
          fi

      - name: Verify image signature
        if: always()
        env:
          COSIGN_EXPERIMENTAL: "1"
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          IMAGE="ghcr.io/${REPO}:${GITHUB_REF_NAME}"
          echo "Verifying signature for ${IMAGE}"
          if ! cosign verify --certificate-oidc-issuer https://token.actions.githubusercontent.com "${IMAGE}" | tee cosign-verify.txt; then
            echo "⚠️ Signature verification failed — this can occur briefly after signing (keyless propagation)." >> "$GITHUB_STEP_SUMMARY"
            echo "Please re-try verification manually after a short delay: cosign verify \"${IMAGE}\"" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "✅ Signature verified successfully for ${IMAGE}" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload cosign verification log
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: cosign-verify
          path: cosign-verify.txt
          retention-days: 7

      - name: "Attest SBOM (required: prefer KMS/key if provided, else keyless OIDC)"
        env:
          COSIGN_EXPERIMENTAL: "1"
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          IMAGE="ghcr.io/${REPO}:${GITHUB_REF_NAME}"
          test -s sbom-image.json
          if [ -n "${COSIGN_KMS_URI:-}" ]; then
            echo "Attesting with KMS: ${COSIGN_KMS_URI}"
            cosign attest --yes --key "${COSIGN_KMS_URI}" --predicate sbom-image.json --type cyclonedx "${IMAGE}"
          elif [ -n "${COSIGN_KEY:-}" ]; then
            echo "Attesting with provided key material"
            echo "${COSIGN_KEY}" > cosign.key
            export COSIGN_PASSWORD="${COSIGN_PASSWORD:-}"
            cosign attest --yes --key cosign.key --predicate sbom-image.json --type cyclonedx "${IMAGE}"
            rm -f cosign.key
          else
            echo "Attesting keylessly via GitHub OIDC"
            cosign attest --yes --predicate sbom-image.json --type cyclonedx "${IMAGE}"
          fi

      - name: Smoke test published image
        env:
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          VERSION=${GITHUB_REF_NAME}
          docker pull ghcr.io/${REPO}:${VERSION}
          docker run --rm ghcr.io/${REPO}:${VERSION} python -m elspeth.cli --help > /dev/null
          echo "✅ Published image runs CLI successfully"
