name: Reusable CI (Lint, Types, Tests)

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"

permissions:
  contents: read

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.lock

      - name: Install dependencies (locked)
        run: |
          python -m pip install -r requirements-dev.lock --require-hashes
          python -m pip install -e . --no-deps --no-index --no-build-isolation

      - name: Restore mypy cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml', 'src/**/*.py') }}
          restore-keys: |
            mypy-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Lint (ruff + mypy)
        run: |
          python -m ruff check src tests
          python -m mypy src

      # Ruff gates both docstrings (D) and security (S) via pyproject config

      - name: Unit tests with coverage
        run: |
          python -m pytest -m "not slow" --maxfail=1 --disable-warnings --cov-fail-under=80 --cov-report=xml:coverage.xml

      - name: Enforce per-file coverage (src/elspeth)
        run: |
          python scripts/check_coverage_thresholds.py \
            --xml coverage.xml \
            --all 0.80 \
            --include-prefix src/elspeth/ \
            --file src/elspeth/core/security/sidecar_client.py:0.0 \
            --file src/elspeth/core/security/digest.py:0.74 \
            --file src/elspeth/core/security/proxy.py:0.61 \
            --file src/elspeth/core/security/secure_data.py:0.62 \
            --file src/elspeth/orchestrator/runtime.py:0.76 \
            --file src/elspeth/orchestrator/worker_process.py:0.55

      - name: Upload coverage xml
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 7
